config/routes.rb
Rails.application.routes.draw do
  root 'kitties#index'
  resources :weapons
  resources :kitties
  get 'kitties/:id/battle' => 'kitties#battle'

end

app/models/kitty.rb
class Kitty < ActiveRecord::Base
  has_many :weapons
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  belongs_to :kitty
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kitties_controller.rb
class KittiesController < ApplicationController
  before_action :set_kitty, only: [:show, :edit, :update, :destroy, :battle]

  # GET /kitties
  # GET /kitties.json
  def index
    @kitties = Kitty.all
  end

  # GET /kitties/1
  # GET /kitties/1.json
  def show
  end

  # GET /kitties/new
  def new
    @kitty = Kitty.new
  end

  # GET /kitties/1/edit
  def edit
  end

  def battle
    @challenger = Kitty.order("RANDOM()").first
    if(rand()>= 0.5)
      @winner = @challenger
      @looser = @kitty
    else
      @winner = @kitty
      @looser = @challenger
    end
    binding.pry if @looser.weapons != []
    @winner.weapons.concat(@looser.weapons.clone)
    @stolen_weapons = @looser.weapons.map{|weapon| weapon.name}
    @looser.weapons = []
    binding.pry if @stolen_weapons == []
    @winner.save
    @looser.save
  end

  # POST /kitties
  # POST /kitties.json
  def create
    @kitty = Kitty.new(kitty_params)

    respond_to do |format|
      if @kitty.save
        format.html { redirect_to @kitty, notice: 'Kitty was successfully created.' }
        format.json { render :show, status: :created, location: @kitty }
      else
        format.html { render :new }
        format.json { render json: @kitty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitties/1
  # PATCH/PUT /kitties/1.json
  def update
    respond_to do |format|
      if @kitty.update(kitty_params)
        format.html { redirect_to @kitty, notice: 'Kitty was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitty }
      else
        format.html { render :edit }
        format.json { render json: @kitty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitties/1
  # DELETE /kitties/1.json
  def destroy
    @kitty.destroy
    respond_to do |format|
      format.html { redirect_to kitties_url, notice: 'Kitty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitty
      @kitty = Kitty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitty_params
      params.require(:kitty).permit(:name, :image)
    end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: [:show, :edit, :update, :destroy]

  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
    @kitties = Kitty.all
  end

  # GET /weapons/1/edit
  def edit
    @kitties = Kitty.all
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1
  # PATCH/PUT /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon.destroy
    respond_to do |format|
      format.html { redirect_to weapons_url, notice: 'Weapon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weapon_params
      params.require(:weapon).permit(:name, :kitty_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kitties_helper.rb
module KittiesHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/kitties/_form.html.erb
<%= form_for(@kitty) do |f| %>
  <% if @kitty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitty.errors.count, "error") %> prohibited this kitty from being saved:</h2>

      <ul>
      <% @kitty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kitties/battle.html.erb
 <%=@winner.name%> defeated <%=@looser.name%> using <%=@winner.weapons.order("RANDOM()").first.try(:name) || "claws and teeth" %><% if @stolen_weapons.any? %> and stole <%= @stolen_weapons.to_sentence || "nothing"%><%end%>


<%= link_to 'Back', kitties_path %>

app/views/kitties/edit.html.erb
<h1>Editing Kitty</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitty %> |
<%= link_to 'Back', kitties_path %>

app/views/kitties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kitties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weapons</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kitties.each do |kitty| %>
      <tr>
        <td><%= kitty.name %></td>
        <td><%= kitty.weapons.count %></td>
        <td><%= link_to 'Edit', edit_kitty_path(kitty) %></td>
        <td><%= link_to 'Battle', "/kitties/#{kitty.id}/battle", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Summon kitty', new_kitty_path %>
<br>
<%= link_to 'Forge new weapon', new_weapon_path %>

app/views/kitties/new.html.erb
<h1>New Kitty</h1>

<%= render 'form' %>

<%= link_to 'Back', kitties_path %>

app/views/kitties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kitty.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @kitty.image %>
</p>

<%= link_to 'Edit', edit_kitty_path(@kitty) %> |
<%= link_to 'Back', kitties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StabbyCat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.select(:kitty_id, options_from_collection_for_select(@kitties, :id, :name)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapons/edit.html.erb
<h1>Editing Weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weapons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kitty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weapons.each do |weapon| %>
      <tr>
        <td><%= weapon.name %></td>
        <td><%= weapon.kitty.try(:name) %></td>
        <td><%= link_to 'Edit', edit_weapon_path(weapon) %></td>
        <td><%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weapon', new_weapon_path %>

<br>
<%= link_to 'Kitties', kitties_path %>

app/views/weapons/new.html.erb
<h1>New Weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weapon.name %>
</p>

<p>
  <strong>Kitty:</strong>
  <%= @weapon.kitty.try(:name) %>
</p>

<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>